**Name - Gaurav Sethi**
**Roll No. - 102317030**
**Subgroup - 3Q-11**
**Assignment-1 (NumPy)**

In [1]:
import numpy as np

In [12]:
# Q1(a)
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Q1(a) Reversed:", reversed_arr)

Q1(a) Reversed: [5 4 6 3 2 1]


In [13]:
# Q1(b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened1 = array1.flatten()
flattened2 = array1.ravel()
print("Q1(b) Flattened1:", flattened1)
print("Q1(b) Flattened2:", flattened2)

Q1(b) Flattened1: [1 2 3 2 4 5 1 2 3]
Q1(b) Flattened2: [1 2 3 2 4 5 1 2 3]


In [4]:
# Q1(c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
are_equal = np.array_equal(arr1, arr2)
print("Q1(c) Are Equal:", are_equal)

Q1(c) Are Equal: True


In [5]:
# Q1(d.i)
x = np.array([1,2,3,4,5,1,2,1,1,1])
values_x, counts_x = np.unique(x, return_counts=True)
max_count_x = np.max(counts_x)
most_freq_x = values_x[counts_x == max_count_x]
indices_x = np.where(x == most_freq_x[0])[0]
print("Q1(d.i) Most Frequent Value:, most_freq_x)
print("Q1(d.i) Indices:", indices_x)

Q1(d.i) Most Frequent Value: [1]
Q1(d.i) Indices: [0 5 7 8 9]


In [6]:
# Q1(d.ii)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values_y, counts_y = np.unique(y, return_counts=True)
max_count_y = np.max(counts_y)
most_freq_y = values_y[counts_y == max_count_y]
indices_y = np.where(y == most_freq_y[0])[0]
print("Q1(d.ii) Most Frequent Value:", most_freq_y)
print("Q1(d.ii) Indices:", indices_y)

Q1(d.ii) Most Frequent Value: [1 3]
Q1(d.ii) Indices: [0 1 2]


In [7]:
# Q1(e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all = gfg.sum()
sum_rows = gfg.sum(axis=1)
sum_cols = gfg.sum(axis=0)
print("Q1(e) Sum All:", sum_all)
print("Q1(e) Sum Rows:", sum_rows)
print("Q1(e) Sum Columns:", sum_cols)

Q1(e) Sum All: 45
Q1(e) Sum Rows: [[14]
 [16]
 [15]]
Q1(e) Sum Columns: [[20  9 16]]


In [8]:
# Q1(f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag_sum = np.trace(n_array)
eig_vals = np.linalg.eigvals(n_array)
eig_vecs = np.linalg.eig(n_array)
inv_matrix = np.linalg.inv(n_array)
det_matrix = np.linalg.det(n_array)
print("Q1(f) Diagonal Sum:", diag_sum)
print("Q1(f) Eigenvalues:", eig_vals)
print("Q1(f) Eigenvectors:", eig_vecs)
print("Q1(f) Inverse:", inv_matrix)
print("Q1(f) Determinant:", det_matrix)

Q1(f) Diagonal Sum: 176
Q1(f) Eigenvalues: [98.16835147 28.097044   49.73460452]
Q1(f) Eigenvectors: EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
Q1(f) Inverse: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Q1(f) Determinant: 137180.0000000001


In [9]:
# Q1(g.i)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
dot1 = np.dot(p1, q1)
cov1 = np.cov(p1, q1)
print("Q1(g.i) Dot Product:", dot1)
print("Q1(g.i) Covariance:", cov1)

Q1(g.i) Dot Product: [[16 19]
 [26 31]]
Q1(g.i) Covariance: [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [10]:
# Q1(g.ii)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
dot2 = np.dot(p2, q2)
cov2 = np.cov(p2.T, q2)
print("Q1(g.ii) Dot Product:", dot2)
print("Q1(g.ii) Covariance:", cov2)

Q1(g.ii) Dot Product: [[16 19  5]
 [26 31  8]
 [46 55 14]]
Q1(g.ii) Covariance: [[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [11]:
# Q1(h) 
x_mat = np.array([[2, 3, 4], [3, 2, 9]])
y_mat = np.array([[1, 5, 0], [5, 10, 3]])
inner_prod = np.inner(x_mat, y_mat)
outer_prod = np.outer(x_mat, y_mat)

a = x_mat.flatten()
b = y_mat.flatten()
A, B = np.meshgrid(a, b)
cartesian_prod = np.vstack([A.ravel(), B.ravel()]).T

print("Q1(h) Inner Product:", inner_prod)
print("Q1(h) Outer Product:", outer_prod)
print("Q1(h) Cartesian Product:", cartesian_prod)

Q1(h) Inner Product: [[17 52]
 [13 62]]
Q1(h) Outer Product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Q1(h) Cartesian Product: [[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


In [14]:
# Q2(a)
array = np.array([[1, -2, 3], [-4, 5, -6]])

In [15]:
# Q2(a.i) Absolute value
abs_array = np.abs(array)
print("Q2(a.i) Absolute Value:\n", abs_array)

Q2(a.i) Absolute Value:
 [[1 2 3]
 [4 5 6]]


In [16]:
# Q2(a.ii) Percentiles
percentile_flat = np.percentile(array.flatten(), [25, 50, 75])
percentile_cols = np.percentile(array, [25, 50, 75], axis=0)
percentile_rows = np.percentile(array, [25, 50, 75], axis=1)
print("Q2(a.ii) Percentiles (Flattened):", percentile_flat)
print("Q2(a.ii) Percentiles (Columns):\n", percentile_cols)
print("Q2(a.ii) Percentiles (Rows):\n", percentile_rows)

Q2(a.ii) Percentiles (Flattened): [-3.5 -0.5  2.5]
Q2(a.ii) Percentiles (Columns):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Q2(a.ii) Percentiles (Rows):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [18]:
# Q2(a.iii) Mean, Median, Std
mean_flat = np.mean(array.flatten())
median_flat = np.median(array.flatten())
std_flat = np.std(array.flatten())
print("Q2(a.iii) Mean (Flattened):", mean_flat)
print("Q2(a.iii) Median (Flattened):", median_flat)
print("Q2(a.iii) Std Dev (Flattened):", std_flat)

mean_cols = np.mean(array, axis=0)
median_cols = np.median(array, axis=0)
std_cols = np.std(array, axis=0)
print("Q2(a.iii) Mean (Columns):", mean_cols)
print("Q2(a.iii) Median (Columns):", median_cols)
print("Q2(a.iii) Std Dev (Columns):", std_cols)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)
print("Q2(a.iii) Mean (Rows):", mean_rows)
print("Q2(a.iii) Median (Rows):", median_rows)
print("Q2(a.iii) Std Dev (Rows):", std_rows)

Q2(a.iii) Mean (Flattened): -0.5
Q2(a.iii) Median (Flattened): -0.5
Q2(a.iii) Std Dev (Flattened): 3.8622100754188224
Q2(a.iii) Mean (Columns): [-1.5  1.5 -1.5]
Q2(a.iii) Median (Columns): [-1.5  1.5 -1.5]
Q2(a.iii) Std Dev (Columns): [2.5 3.5 4.5]
Q2(a.iii) Mean (Rows): [ 0.66666667 -1.66666667]
Q2(a.iii) Median (Rows): [ 1. -4.]
Q2(a.iii) Std Dev (Rows): [2.05480467 4.78423336]


In [19]:
# Q2(b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_a = np.floor(a)
ceil_a = np.ceil(a)
trunc_a = np.trunc(a)
round_a = np.round(a)

print("Q2(b) Floor:", floor_a)
print("Q2(b) Ceil:", ceil_a)
print("Q2(b) Trunc:", trunc_a)
print("Q2(b) Round:", round_a)

Q2(b) Floor: [-2. -2. -1.  0.  1.  1.  3.]
Q2(b) Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Q2(b) Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Q2(b) Round: [-2. -2. -0.  0.  2.  2.  3.]


In [20]:
# Q3. Given array
arr = np.array([3.5, 2, 8.9, 5, 0, 12, 7.1, 4, 3, 1.5, 6.3, 11, 9.8, 10, 2.5])

In [21]:
# Q3(a) 
sorted_arr = np.sort(arr)
print("Q3(a) Sorted array:", sorted_arr)

Q3(a) Sorted array: [ 0.   1.5  2.   2.5  3.   3.5  4.   5.   6.3  7.1  8.9  9.8 10.  11.
 12. ]


In [22]:
# Q3(b) 
sorted_indices = np.argsort(arr)
print("Q3(b) Indices that would sort the array:", sorted_indices)

Q3(b) Indices that would sort the array: [ 4  9  1 14  8  0  7  3 10  6  2 12 13 11  5]


In [23]:
# Q3(c) 
four_smallest = np.sort(arr)[:4]
print("Q3(c) Four smallest elements:", four_smallest)

Q3(c) Four smallest elements: [0.  1.5 2.  2.5]


In [24]:
# Q3(d) 
five_largest = np.sort(arr)[-5:]
print("Q3(d) Five largest elements:", five_largest)

Q3(d) Five largest elements: [ 8.9  9.8 10.  11.  12. ]


In [25]:
# Q3(e) 
integer_elements = arr[arr == arr.astype(int)]
print("Q3(e) Integer elements:", integer_elements)

Q3(e) Integer elements: [ 2.  5.  0. 12.  4.  3. 11. 10.]


In [26]:
# Q3(f) 
float_elements = arr[arr != arr.astype(int)]
print("Q3(f) Float elements:", float_elements)

Q3(f) Float elements: [3.5 8.9 7.1 1.5 6.3 9.8 2.5]


In [ ]:
# Q4
from PIL import Image
import numpy as np

def img_to_array(path):
    img=Image.open(path)
    arr=np.array(img)
    if len(arr.shape)==2:
        np.savetxt("grayscale_image.txt",arr,fmt='%d')
    else:
        np.savetxt("rgb_image.txt",arr.reshape(-1,arr.shape[2]),fmt='%d')


gray = np.loadtxt("grayscale_image.txt", dtype=int)
rgb = np.loadtxt("rgb_image.txt", dtype=int)